<template>
    <Header></Header>
    <!--Video></Video-->
    <!--Starfield/-->
    <AdLunam></AdLunam>
    <Projects></Projects>
    <Departments></Departments>
    <LastBlog></LastBlog>
    <Partners></Partners>
    <Footer></Footer>
</template>